/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.uma.VeRxina;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {

        // Lは、Longの意味。
        long data = 1L;
        System.out.println(data);


    }
}
