/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.uma.VeRxina;

import io.reactivex.Flowable;
import io.reactivex.disposables.Disposable;

public class App {

    public static void main(String[] args) {

        Flowable<String> flowable = Flowable.just("hello", "world");
        Disposable aa = flowable.subscribe(i -> System.out.println(i));



    }


}
